### ISSUE TITLE
Problem in compilation

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [rdlaitila/maillog2db#4]
Hello, when I type `go build`, it says to me : 

` ./maillog2db.go:158: cannot assign *gorm.DB to DBCONN (type gorm.DB) in multiple assignment`

My system :
```

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
root@smtp-out:/opt/maillog2db# go version
go version go1.6.2 linux/amd64
```

Can you help me ? Thank you !

**Comment by rdlaitila** [comment]
I've fixed a pointer issue that was causing the build error. Please pull latest and let know if you see any further issues. Thanks!

**Comment by NicolasDEVOUGE** [comment]
I have pulled the repo, everything is fine now, thank you !
